export const ACTIVITY_CONFIG = {
    'Spiritual': [
        { name: 'Ancestral Altars/Veneration', duration: 30, preferredWindow: 'Morning' },
        { name: 'Traditional Chant or Mantra', duration: 20, preferredWindow: 'Morning' },
        { name: 'Silent Meditation on Lineage', duration: 30, preferredWindow: 'Morning' },
        { name: 'Mindful Breathing/Pranayama', duration: 15, preferredWindow: 'Morning' },
        { name: 'Morning Offering Ritual', duration: 20, preferredWindow: 'Morning' },
        { name: 'Community Prayer/Gathering', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Sacred Geometry Drawing', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Temple or Shrine Cleaning', duration: 40, preferredWindow: 'Afternoon' },
        { name: 'Zen Garden Maintenance', duration: 30, preferredWindow: 'Afternoon' },
        { name: 'Walking Meditation', duration: 20, preferredWindow: 'Afternoon' },
        { name: 'Cultural Sacred Text Study', duration: 45, preferredWindow: 'Evening' },
        { name: 'Traditional Tea/Incense Ceremony', duration: 30, preferredWindow: 'Evening' },
        { name: 'Listening to Spiritual Elders', duration: 45, preferredWindow: 'Evening' },
        { name: 'Reflection on Ancestral Wisdom', duration: 30, preferredWindow: 'Evening' },
        { name: 'Evening Gratitude Journaling', duration: 20, preferredWindow: 'Evening' }
    ],
    'Wellness': [
        { name: 'Traditional Movement (e.g., Tai Chi)', duration: 45, preferredWindow: 'Morning' },
        { name: 'Ancient Breathing Techniques', duration: 15, preferredWindow: 'Morning' },
        { name: 'Nature Walk in Sacred Spaces', duration: 60, preferredWindow: 'Morning' },
        { name: 'Sun Salutations/Morning Ritual', duration: 30, preferredWindow: 'Morning' },
        { name: 'Cold Water Face/Body Wash', duration: 10, preferredWindow: 'Morning' },
        { name: 'Indigenous Herbal Medicine Prep', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Seasonal Eating Plan', duration: 30, preferredWindow: 'Afternoon' },
        { name: 'Communal Wellness Circle', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Mindful Stretching', duration: 25, preferredWindow: 'Afternoon' },
        { name: 'Herbal Tea Blending', duration: 20, preferredWindow: 'Afternoon' },
        { name: 'Heritage Bathing Ritual', duration: 40, preferredWindow: 'Evening' },
        { name: 'Traditional Acupressure/Massage', duration: 45, preferredWindow: 'Evening' },
        { name: 'Dream Journaling/Interpretation', duration: 20, preferredWindow: 'Evening' },
        { name: 'Evening Foot Soak/Ritual', duration: 15, preferredWindow: 'Evening' },
        { name: 'Moonlight Meditation', duration: 20, preferredWindow: 'Evening' }
    ],
    'Music': [
        { name: 'Folk Instrument Practice', duration: 60, preferredWindow: 'Morning' },
        { name: 'Vocal Warmups (Heritage Scales)', duration: 20, preferredWindow: 'Morning' },
        { name: 'Percussion Drill/Technique', duration: 45, preferredWindow: 'Morning' },
        { name: 'Rhythm Clapping Patterns', duration: 15, preferredWindow: 'Morning' },
        { name: 'Instrument Maintenance', duration: 25, preferredWindow: 'Morning' },
        { name: 'Studying Rhythms', duration: 30, preferredWindow: 'Afternoon' },
        { name: 'Transcribing Folk Melodies', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Studying Lives of Folk Masters', duration: 45, preferredWindow: 'Afternoon' },
        { name: 'Heritage Scale Exploration', duration: 30, preferredWindow: 'Afternoon' },
        { name: 'Melodic Ear Training', duration: 20, preferredWindow: 'Afternoon' },
        { name: 'Learning Traditional Ballads', duration: 45, preferredWindow: 'Evening' },
        { name: 'Translating Heritage Songs', duration: 60, preferredWindow: 'Evening' },
        { name: 'Listening to Cultural Archives', duration: 40, preferredWindow: 'Evening' },
        { name: 'Composing in Cultural Modes', duration: 60, preferredWindow: 'Evening' },
        { name: 'Deep Listening Session', duration: 30, preferredWindow: 'Evening' }
    ],
    'Performing Arts': [
        { name: 'Folk Performance Drill', duration: 30, preferredWindow: 'Morning' },
        { name: 'Gesture & Mudra Practice', duration: 30, preferredWindow: 'Morning' },
        { name: 'Studying Epic Theatre', duration: 90, preferredWindow: 'Morning' },
        { name: 'Facial Expression Training', duration: 20, preferredWindow: 'Morning' },
        { name: 'Vocal Projection Exercise', duration: 15, preferredWindow: 'Morning' },
        { name: 'Heritage Dance Rehearsal', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Cultural Mask Work', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Heritage Costume Repair', duration: 45, preferredWindow: 'Afternoon' },
        { name: 'Blocking a Traditional Scene', duration: 40, preferredWindow: 'Afternoon' },
        { name: 'Prop Making for Performance', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Traditional Oral Storytelling', duration: 45, preferredWindow: 'Evening' },
        { name: 'Ancestral Play Study', duration: 120, preferredWindow: 'Evening' },
        { name: 'Puppetry/Shadow Work', duration: 60, preferredWindow: 'Evening' },
        { name: 'Improv based on Folklore', duration: 60, preferredWindow: 'Evening' },
        { name: 'Character Deep Dive', duration: 30, preferredWindow: 'Evening' }
    ],
    'Visual Arts': [
        { name: 'Traditional Pattern Design', duration: 45, preferredWindow: 'Morning' },
        { name: 'Heritage Calligraphy/Script', duration: 60, preferredWindow: 'Morning' },
        { name: 'Natural Pigment Mixing', duration: 60, preferredWindow: 'Morning' },
        { name: 'Ink Grinding/Preparation', duration: 20, preferredWindow: 'Morning' },
        { name: 'Daily Sketching (Heritage Themes)', duration: 30, preferredWindow: 'Morning' },
        { name: 'Indigenous Textile Art', duration: 120, preferredWindow: 'Afternoon' },
        { name: 'Traditional Pottery Work', duration: 120, preferredWindow: 'Afternoon' },
        { name: 'Woodblock Print Design', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Symbolic Mural Sketching', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Fiber Arts/Spinning', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Sacred Symbolism Study', duration: 90, preferredWindow: 'Evening' },
        { name: 'Restoring Family Photos/Art', duration: 45, preferredWindow: 'Evening' },
        { name: 'Learning Ancient Iconography', duration: 60, preferredWindow: 'Evening' },
        { name: 'Color Palette Development', duration: 30, preferredWindow: 'Evening' },
        { name: 'Reviewing Traditional Artists', duration: 40, preferredWindow: 'Evening' }
    ],
    'Literature': [
        { name: 'Learning Native Language', duration: 45, preferredWindow: 'Morning' },
        { name: 'Writing in Heritage Script', duration: 30, preferredWindow: 'Morning' },
        { name: 'Studying Ancient Poetry', duration: 45, preferredWindow: 'Morning' },
        { name: 'Heritage Vocabulary Drill', duration: 20, preferredWindow: 'Morning' },
        { name: 'Language Listening Practice', duration: 30, preferredWindow: 'Morning' },
        { name: 'Researching Genealogy', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Translating Family Letters', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Oral History Transcription', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Documenting Family Lore', duration: 45, preferredWindow: 'Afternoon' },
        { name: 'Archival Photo Organization', duration: 30, preferredWindow: 'Afternoon' },
        { name: 'Reading Post-Colonial Literature', duration: 60, preferredWindow: 'Evening' },
        { name: 'Analyzing Cultural Myths', duration: 45, preferredWindow: 'Evening' },
        { name: 'Reviewing Cultural Essays', duration: 45, preferredWindow: 'Evening' },
        { name: 'Writing Original Folk Tales', duration: 60, preferredWindow: 'Evening' },
        { name: 'Reading Cultural Biographies', duration: 40, preferredWindow: 'Evening' }
    ],
    'Culinary': [
        { name: 'Fermenting Traditional Foods', duration: 45, preferredWindow: 'Morning' },
        { name: 'Heritage Spice Sourcing', duration: 30, preferredWindow: 'Morning' },
        { name: 'Baking Traditional Breads', duration: 120, preferredWindow: 'Morning' },
        { name: 'Knife Skills/Traditional Cuts', duration: 30, preferredWindow: 'Morning' },
        { name: 'Morning Dough Prep', duration: 20, preferredWindow: 'Morning' },
        { name: 'Cooking Grandmother’s Recipe', duration: 120, preferredWindow: 'Afternoon' },
        { name: 'Preserving Cultural Crops', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Traditional Beverage Brewing', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Pickling Heritage Veggies', duration: 40, preferredWindow: 'Afternoon' },
        { name: 'Kitchen Organization/Tool Care', duration: 30, preferredWindow: 'Afternoon' },
        { name: 'Ceremonial Plating', duration: 40, preferredWindow: 'Evening' },
        { name: 'Studying Culinary History', duration: 45, preferredWindow: 'Evening' },
        { name: 'Seasonal Feast Planning', duration: 45, preferredWindow: 'Evening' },
        { name: 'Traditional Dining Etiquette', duration: 30, preferredWindow: 'Evening' },
        { name: 'Recipe Journaling', duration: 30, preferredWindow: 'Evening' }
    ],
    'Crafts': [
        { name: 'Making Cultural Adornments', duration: 60, preferredWindow: 'Morning' },
        { name: 'Leatherwork/Traditional Tooling', duration: 90, preferredWindow: 'Morning' },
        { name: 'Natural Fiber Spinning', duration: 60, preferredWindow: 'Morning' },
        { name: 'Tool Sharpening/Prep', duration: 25, preferredWindow: 'Morning' },
        { name: 'Daily Weaving Drill', duration: 30, preferredWindow: 'Morning' },
        { name: 'Traditional Weaving', duration: 120, preferredWindow: 'Afternoon' },
        { name: 'Heritage Woodcarving', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Traditional Basketry', duration: 120, preferredWindow: 'Afternoon' },
        { name: 'Pottery Decoration/Glazing', duration: 45, preferredWindow: 'Afternoon' },
        { name: 'Natural Dye Extraction', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Symbolic Embroidery', duration: 45, preferredWindow: 'Evening' },
        { name: 'Beadwork/Symbolic Patterns', duration: 60, preferredWindow: 'Evening' },
        { name: 'Traditional Toy Making', duration: 60, preferredWindow: 'Evening' },
        { name: 'Knotted Cord Work/Macrame', duration: 40, preferredWindow: 'Evening' },
        { name: 'Refining Small Details', duration: 30, preferredWindow: 'Evening' }
    ],
    'Exploration': [
        { name: 'Heritage Landmark Pilgrimage', duration: 180, preferredWindow: 'Morning' },
        { name: 'Traditional Marketplace Visit', duration: 60, preferredWindow: 'Morning' },
        { name: 'Local Archive Research', duration: 90, preferredWindow: 'Morning' },
        { name: 'Street Photography (Heritage)', duration: 60, preferredWindow: 'Morning' },
        { name: 'Neighborhood History Mapping', duration: 45, preferredWindow: 'Morning' },
        { name: 'Visiting Cultural Neighborhoods', duration: 120, preferredWindow: 'Afternoon' },
        { name: 'Connecting with Cultural Elders', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Exploring Heritage Museums', duration: 120, preferredWindow: 'Afternoon' },
        { name: 'Documenting Heritage Murals', duration: 60, preferredWindow: 'Afternoon' },
        { name: 'Visiting Local Craft Studios', duration: 90, preferredWindow: 'Afternoon' },
        { name: 'Documenting Oral History', duration: 60, preferredWindow: 'Evening' },
        { name: 'Attending Cultural Festivals', duration: 180, preferredWindow: 'Evening' },
        { name: 'Listening to Community Radio', duration: 45, preferredWindow: 'Evening' },
        { name: 'Watching Heritage Documentaries', duration: 90, preferredWindow: 'Evening' },
        { name: 'Planning Future Pilgrimages', duration: 40, preferredWindow: 'Evening' }
    ]
};